routes/web.php
<?php

use App\Http\Controllers\PagesController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
Route::get('/hello', function () {
    return '<h1>Hello World!</h1>';
});
//Kaip padaryti Dynamic Route. Pvz: įvedus http://127.0.0.1:8000/users/27/Robertas į URL
Route::get('/users/{id}/{name}', function ($id, $name) {
    return 'This is user '.$name. ' with an ID of '.$id;
});
*/

Route::get('/', 'PagesController@index');
Route::get('/about', 'PagesController@about');
Route::get('/services', 'PagesController@services');

Route::resource('posts', 'PostsController');



Auth::routes();

Route::get('/dashboard', 'DashboardController@index');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    // Table Name, default postu pavadinimai butu "Posts" nes sukurem model pavadinimu "Post", bet galima pakeisti:
    protected $table = 'posts';
    // Taip pat galima pakeisti Primary Key field
    public $primaryKey = 'id';
    // Timestamps
    public $timestamps = true;

    //Sukurti Relationship, Postai, kurie priklauso atitinkamui accountui
    public function user() {
        return $this->belongsTo('App\User');
    }
}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use App\Post;
//Nenaudojant Eloquent, galima naudoti pacias SQL Queries
use DB;

class PostsController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    //Idėti galimybe svečiams matyti postus, bet ne kurti ar trinti. su exceptions: ['except' => ['index', 'show]] 
    public function __construct()
    {
        $this->middleware('auth', ['except' => ['index', 'show']]);
    }

    //index - listing of all the posts
    //create - function to represent the create form \ add posts
    //store - function to submit to the model to the database
    //edit - to edit posts with edit form, which then submits to update method(function)
    //update - actually updates to the database
    //show - to show a single post
    //estrou - function to delete posts
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //$posts = Post::all();

        //Galima padaryti, kad rodytu by order
        //$posts = Post::orderBy('title', 'asc')->get();
        //$posts = Post::orderBy('created_at', 'desc')->get();

        //Galima riboti, kiek rodys vienu metu
        //$posts = Post::orderBy('created_at', 'desc')->take(1)->get();

        //Ideti puslapius, kurie riboja, kiek rodys postu per puslapi, naudojant Paginate, bet reikia ideti papildomai linka i postu blade.php
        $posts = Post::orderBy('created_at', 'desc')->paginate(5);

        //Galima, kad rodytu individualiai kazkoki nurodant specifiskai
        //return Post::where('title', 'Post One')->get();

        //Nauojant DB Queries
        //$posts = DB::select('SELECT * FROM posts');

        return view('posts.index')->with('posts', $posts);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('posts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required',
            'body' => 'required',
            'cover_image' => 'image|nullable|max:1999'
        ]);

        // Handle File Upload
        if($request->hasFile('cover_image')) {
            // Get filename with the extension
            $fileNameWithExt = $request->file('cover_image')->getClientOriginalName();
            // Get just filename
            $filename = pathinfo($fileNameWithExt, PATHINFO_FILENAME);
            // Get just extension
            $extension = $request->file('cover_image')->getClientOriginalExtension();
            //Filename to store
            $fileNameToStore = $filename.'_'.time().'.'.$extension;
            // Upload Image
            $path = $request->file('cover_image')->storeAs('public/cover_images', $fileNameToStore);
        } else {
            $fileNameToStore = 'noimage.png';
        }

        // Create Post
        $post = new Post;
        $post->title = $request->input('title');
        $post->body = $request->input('body');
        $post->user_id = auth()->user()->id;
        $post->cover_image = $fileNameToStore;
        $post->save();

        return redirect('/posts')->with('success', 'Postas Sukurtas Sėkmingai!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post = Post::find($id);
        return view('posts.show')->with('post', $post);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = Post::find($id);

        //Check the correct user for ability to edit
        if(auth()->user()->id !== $post->user_id) {
            return redirect('/posts')->with('error', 'Jūs nesate šio posto autorius');
        }

        return view('posts.edit')->with('post', $post);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'title' => 'required',
            'body' => 'required',
            'cover_image' => 'image|nullable|max:1999'
        ]);

        // Handle File Upload
        if($request->hasFile('cover_image')) {
            // Get filename with the extension
            $fileNameWithExt = $request->file('cover_image')->getClientOriginalName();
            // Get just filename
            $filename = pathinfo($fileNameWithExt, PATHINFO_FILENAME);
            // Get just extension
            $extension = $request->file('cover_image')->getClientOriginalExtension();
            //Filename to store
            $fileNameToStore = $filename.'_'.time().'.'.$extension;
            // Upload Image
            $path = $request->file('cover_image')->storeAs('public/cover_images', $fileNameToStore);
        }

        // Create Post
        $post = Post::find($id);

        //Check the correct user for ability to update, in case of csrf defence breach
        if(auth()->user()->id !== $post->user_id) {
            return redirect('/posts')->with('error', 'Jūs nesate šio posto autorius');
        }

        $post->title = $request->input('title');
        $post->body = $request->input('body');
        if($request->hasFile('cover_image')) {
            $post->cover_image = $fileNameToStore;
        }

        $post->save();

        return redirect('/posts')->with('success', 'Postas Paredaguotas!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = Post::find($id);

        //Check the correct user for ability to delete
        if(auth()->user()->id !== $post->user_id) {
            return redirect('/posts')->with('error', 'Jūs nesate šio posto autorius');
        }

        // Kai postas trinamas, kad issitrintu ir pats uploadintas paveikslas
        if($post->cover_image != 'noimage.png') {
            // Delete the image
            Storage::delete('public/cover_images/'.$post->cover_image);
        }

        $post->delete();
        return redirect('/posts')->with('success', 'Postas Sunaikintas');
    }
}

resources/views/posts/create.blade.php
@extends('layouts.app')

@section('content')
    <h1>Create Post</h1>
    <form method="post" action="{{ route('posts.store') }}" enctype="multipart/form-data">
        <div class="form-group">
            @csrf            
            <label for="title">Title</label>
            <input type="text" class="form-control" name="title" placeholder="Title"/>
        </div>
        <div class="form-group">
            <label for="body">Body</label>
            <textarea class="form-control" id="editor1" name="body" cols="30" rows="10" placeholder="Body Text"></textarea>
        </div>
        <div class="form-group">
            <input type="file" name="cover_image">
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
@endsection

resources/views/posts/edit.blade.php
@extends('layouts.app')

@section('content')
    <h1>Edit Post</h1>
    <form method="post" action="{{ route('posts.update', $post->id) }}" enctype="multipart/form-data">
        {{ method_field('PUT') }}
        {{ csrf_field() }}
        <div class="form-group">
            @csrf            
            <label for="title">Title</label>
            <input type="text" class="form-control" name="title" value="{{$post->title}}"/>
        </div>
        <div class="form-group">
            <label for="body">Body</label>
            <textarea class="form-control" id="editor1" name="body" cols="30" rows="10">{{$post->body}}</textarea>
        </div>
        <div class="form-group">
            <input type="file" name="cover_image">
        </div>

        <button type="submit" class="btn btn-warning">Redaguoti</button>
    </form>
@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')

@section('content')
    <h1>Posts</h1>
    @if(count($posts) > 0)
        @foreach ($posts as $post)
            <div class="card p-3 mt-3 mb-3 bg-secondary text-white">
                <div class="row">
                    <div class="col-md-4 col-sm-4">
                        <img style="width:100%" src="/storage/cover_images/{{$post->cover_image}}" alt="">
                    </div>
                    <div class="col-md-8 col-sm-8">
                        <h3><a class="text-white" href="/posts/{{$post->id}}">{{$post->title}}</a></h3>
                        <small>Sukurtas: {{$post->created_at}} Vartotojo: {{$post->user->name}}</small>
                    </div>
                </div>
            </div>
        @endforeach
        <!-- Pagination linkai is PostsController -->
        {{$posts->links()}}
    @else
        <p>Nėra jokių postų</p>
    @endif
@endsection

resources/views/posts/show.blade.php
@extends('layouts.app')

@section('content')
    <a href="/posts" class="btn btn-secondary mb-3">Atgal</a>
    <h1 class="jumbotron text-center">{{$post->title}}</h1>
    <img style="width:100%" src="/storage/cover_images/{{$post->cover_image}}" alt="">
    <br><br>
    <div>
        <!-- Kad Parsintu posta su visokiais bold, italic, listais ir pns...
            reikia taip, su dviem sauktukais: {//{!//!$post->body!!}} ignore "//" -->
        {!!$post->body!!}
    </div>
    <hr>
    <small>Sukurtas: {{$post->created_at}} Vartotojo: {{$post->user->name}}</small>
    <hr>
    @if (!Auth::guest())
        @if (Auth::user()->id == $post->user_id)
            <a href="/posts/{{$post->id}}/edit" class="btn btn-outline-warning">Redaguoti</a>

            <form method="POST" class="delete_form float-right" action="{{ action('PostsController@destroy', $post->id) }}">
                {{ csrf_field() }}
                <input type="hidden" name="_method" value="DELETE">
                <button type="submit" class="btn btn-danger">X</button>
            </form>
        @endif
    @endif

    <script>
        $(document).ready(function() {
            $('.delete_form').on('submit', function() {
                if(confirm("Ar tikrai norite panaikinti?")) {
                    return true;
                } else {
                    return false;
                }
            })
        });
    </script>
@endsection